name: Build Docker Image

on:
  workflow_call:

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app/

      - name: Login to DockerHub
        run:
            echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USER}} --password-stdout

      - name: Build Docker Image
        run: 
          docker build -t ${{ secrets.DOCKERHUB_USER }}/myapp:${{ github.sha }} .

      - name: Tag Image
        run: 
          docker tag ${{ secrets.DOCKERHUB_USER }}/myapp:${{ github.sha }} ${{ secrets.DOCKERHUB_USER }}/myapp:latest

      - name: Push Image
        run: 
          docker push ${{ secrets.DOCKERHUB_USER }}/myapp:latest
