name: Deploy to EKS

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true


jobs:
  deploy:
    runs-on: self-hosted

    env:
      IMAGE: ${{ secrets.DOCKERHUB_USER }}/myapp:latest


    steps:
      - uses: actions/checkout@v4

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-south-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name my-eks --region ap-south-1

    #   - name: Update Deployment Image
    #     run: |
    #       kubectl set image deployment/myapp-deployment myapp=${{ secrets.ECR_URL }}/myapp:latest


      - name: Update image in deployment.yaml
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.IMAGE }}|g" ds.yml
          
      - name: verify node
        run: 
          kubectl get nodes

      - name: Deploy to EKS
        run: |
          kubectl apply -f ds.yml 
